# Generated by Django 3.2.23 on 2025-09-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='type',
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('Feedback', 'Feedback'), ('Complaint', 'Complaint')], default='Feedback', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
