# Generated by Django 3.2.23 on 2025-09-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250905_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelerprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
