# Generated by Django 3.2.23 on 2025-09-05 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_travelerprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
