# Generated by Django 3.2.23 on 2025-09-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
