# Generated by Django 3.2.23 on 2025-09-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250906_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travelerprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
