# Generated by Django 3.2.23 on 2025-09-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_travelerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='user',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans_created', to='core.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelplan',
            name='suggested_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans_suggested', to='core.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='theme',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('family', 'Family'), ('solo', 'Solo')], max_length=50),
        ),
    ]
