# Generated by Django 3.2.23 on 2025-09-20 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250920_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='travelpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='travelpost',
            name='user',
        ),
        migrations.AddField(
            model_name='travelpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='travelpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='photo',
            field=models.ImageField(upload_to='travel_photos/'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='theme',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('family', 'Family'), ('solo', 'Solo')], max_length=50),
        ),
    ]
